services:
  - type: web
    name: answerthepublic-enterprise
    runtime: node
    plan: free
    buildCommand: yarn install || npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
